# Generated by Django 3.1.3 on 2020-11-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearID', models.IntegerField()),
                ('pTT_ID', models.IntegerField()),
                ('capture_lat', models.FloatField()),
                ('capture_long', models.FloatField()),
                ('sex', models.TextField()),
                ('age_class', models.TextField()),
                ('ear_applied', models.TextField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
