# Generated by Django 3.1.3 on 2020-11-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bear',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
