# Generated by Django 3.1.3 on 2020-11-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0002_auto_20201126_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bear_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='bears.bear')),
            ],
        ),
    ]
