# Generated by Django 3.1.3 on 2020-11-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0003_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='deploy_id',
            field=models.IntegerField(default=None),
        ),
    ]
